var facts = [
  "Mercury & Venus are the only 2 planets in our solar system that have no moons.",
  "If a star passes too close to a black hole, it can be torn apart.",
  "Enceladus, one of Saturn�s smaller moons, reflects 90% of the Sun�s light.",
  "The Whirlpool Galaxy (M51) was the first celestial object identified as being Spiral Galaxy",
  "A light-year is the distance covered by light in a single year. The Milky Way galaxy is 105,700 light-years wide.",
  "Footprints left on the Moon won't disappear as there is no wind.",
  "The Martian day is 24 hours 39 minutes and 35 seconds long. Almost Same to Earth.",
  "NASA's Crater Observation and Sensing Satellite (LCROSS) found evidence of water on the Earth�s Moon.",
  "The Sun makes a full rotation once every 25 to 35 days.",
  "Earth is the only planet not named after a God.",
  "Pluto is smaller than the United States.",
  "According to mathematics, white holes are possible, although as of yet we have found none. SPOILER: White Holes Pushes things way at the speed of Light",
  "There are more volcanoes on Venus than any other planet in our solar system.",
  "Because of its unique tilt, a season on Uranus is equivalent to 21 Earth years. Well Think about Summer Leave in Uranus.",
  "There are more stars in space than there are grains of sand in the world.",
  "Neptune takes nearly 165 Earth years to make one orbit of the Sun. Don't even think about School there.",
  "Pluto�s largest moon, Charon, is half the size of Pluto.",
  "The International Space Station is the largest manned object ever sent into space.",
  "A day on Pluto is lasts for 153.6 hours long.",
  "Any free-moving liquid in outer space will form itself into a sphere.",
  "We know more about Mars and our Moon than we do about our Earth's oceans.",
  "The Black Arrow is the only British satellite to be launched using a British rocket.",
  "Only 5% of the universe is visible from Earth. Others are Dark Matter and Dark Energy which can't be seen becoz they are playing Hide and Seek with us.",
  "Light travels from the Sun to the Earth in less than 10 minutes.",
  "At any given moment, there are at least 2,000 thunderstorms happening on Earth.",
  "The Earth�s rotation is slowing slightly as time goes on.",
  "If you were driving at 75 miles per hour, it would take 258 days to drive around Saturn�s rings.",
  "The International Space Station circles Earth every 92 minutes.",
  "We always see the same side of the Moon, no matter where we stand on Earth.",
  "There are three main types of galaxies: elliptical, spiral & irregular.",
  "There are approximately 100 thousand million stars in the Milky Way.",
  "Using the naked eye, you can see 3 � 7 different galaxies from Earth.",
  "In 2016, scientists detected a radio signal from a source 5 billion light-years away.",
  "The first Supernovae observed outside of our own galaxy was in 1885.",
  "The closest galaxy to us is the Andromeda Galaxy � it�s estimated at 2.5 million light-years away.",
  "The first Supernovae observed outside of our own galaxy was in 1885.",
  "The first ever black hole photographed is 3 million times the size of Earth.",
  "The distance between the Sun & Earth is defined as an Astronomical Unit.",
  "The second man on the moon was Buzz Aldrin. �Moon� was Aldrin�s mother�s maiden name.",
  "Astronaut Buzz Aldrin�s birth name was Edwin Eugene Aldrin Jr.",
  "On Venus, it snows metal and rains sulfuric acid.",
  "The Mariner 10 was the first spacecraft that visited Mercury in 1974.",
  "Space is completely silent like a Library.",
  "Coca-Cola was the first commercial soft drink that was ever consumed in space. No need to worry about Drinks in Space.",
  "Astronauts can grow approximately two inches (5 cm) in height when in space due to low Gravity.",
  "The first woman in space was a Russian called Valentina Tereshkova.",
  "The Kuiper Belt is a region of the Solar System beyond the orbit of Neptune.",
  "If Saturn's rings were 3 feet long, they would be 10,000 times thinner than a razorblade.",
  "The Hubble Space Telescope is one of the most productive scientific instruments ever built.",
  "The first artificial satellite in space was called �Sputnik�.",
  "Exoplanets are planets that orbit around other stars.",
  "The center of the Milky Way smells like rum & tastes like raspberries.",
  "Our moon is moving away from Earth at a rate of 1.6 inch (4 cm) per year!",
  "Pluto is named after the Roman god of the underworld, not the Disney Dog.",
  "Spacesuit helmets have a Velcro patch, to help astronauts itch.",
  "The ISS is visible to more than 90% of the Earth�s population.",
  "Saturn is the only planet that could float in water due to its low Density",
  "Asteroids are the byproducts of formations in the solar system, more than 4 billion years ago.",
  "Astronauts can�t burp in space.",
  "Uranus was originally called �George�s Star�.",
  "A sunset on Mars is blue.",
  "The Earth weighs about 81 times more than the Moon.",
  "The first living mammal to go into space was a dog named �Laika� from Russia.",
  "The word �astronaut� means �star sailor� in its origins.",
  "�NASA� stands for National Aeronautics and Space Administration.",
  "ISRO is in 4th Position in Space and Technology",
  "The Fact is I don't have a Fact",
  "Gennady Padalka has spent more time in space than anyone else.",
  "Mercury has no atmosphere, which means there is no wind or weather.",
  "In China, the Milky Way is known as the �Silver River�.",
  "Red Dwarf stars that are low in mass can burn continually for up to 10 trillion years!",
  "Scientists once believed that the same side of Mercury always faced the Sun.",
  "Jupiter�s Red Spot is shrinking.",
  "A large percentage of asteroids are pulled in by Jupiter�s gravity.",
  "A day on Mercury is equivalent to 58 Earth days.",
  "As space has no gravity, pens won�t work.",
  "Buzz Lightyear from Toy Story has actually been to outer space!",
  "There is a planet half the radius of the Earth with a surface made up of diamonds. Find it in Google.",
  "Halley�s Comet will pass over Earth again on 26th July 2061.",
  "Mars is the most likely planet in our solar system to be hospitable to life.",
  "There are 5 Dwarf Planets recognized in our Solar System.",
  "In 2006, the International Astronomical Union reclassified Pluto as a dwarf planet.",
  "As early as 240BC the Chinese began to document the appearance of Halley�s Comet.",
  "The center of a comet is called a �nucleus�.",
  "There are 88 recognized star constellations in our night sky.",
  "On average it takes the light only 1.3 seconds to travel from the Moon to Earth.",
  "As space has no gravity, pens won�t work.",
  'The scientific term for brain freeze is **sphenopalatine ganglioneuralgia**',
  'Canadians say **sorry** so much that a law was passed in 2009 declaring that an apology can’t be used as evidence of admission to guilt',
  'Back when dinosaurs existed, there used to be volcanoes that were erupting on the moon',
  'The only letter that doesn’t appear on the periodic table is J',
  'One habit of intelligent humans is being easily annoyed by people around them, but saying nothing in order to avoid a meaningless argument',
  'If a Polar Bear and a Grizzly Bear met, their offspring is called a **Pizzy Bear**',    
  'In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola',    
  'There were two AI chatbots created by Facebook to talk to each other, but they were shut down after they started communicating in a language they made for themselves.',
  'Nintendo trademarked the phrase “It’s on like Donkey Kong” in 2010'

];

let quotes = [
  "Success is walking from failure to failure with no loss of enthusiasm -Winston Churchill",
  "A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done. -Vince Lombardi",
  "Don't let the fear of losing be greater than the excitement of winning.-Robert Kiyosaki",
	"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.-Jane Smiley",
	"You can do anything, but not everything.-Anonymous",
	"Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.-Theodore N. Vail",
	"Fortune sides with him who dares.-Virgil",
	"The ones who are crazy enough to think they can change the world, are the ones that do.-Anonymous",
	"People rarely succeed unless they have fun in what they are doing.-Dale Carnegie",
	"Don't be afraid to give up the good to go for the great - John D. Rockefeller",
	"You've got to get up every morning with determination if you're going to go to bed with satisfaction.-George Lorimer",
	"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed - Ray Goforth",
	"You may only succeed if you desire succeeding; you may only fail if you do not mind failing.-Philippos",
	"You must expect great things of yourself before you can do them - Michael Jordan",
	"No one can make you feel inferior without your consent.-Eleanor Roosevelt",
	"Successful people do what unsuccessful people are not willing to doDon't wish it were easier, wish you were better.-Jim Rohn",
	"Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.-Anonymous ",
	"If you are not willing to risk the usual you will have to settle for the ordinary.-Jim Rohn",
	"Take up one idea. Make that one idea your life -- think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.-Swami Vivekananda",
	"The number one reason people fail in life is because they listen to their friends, family, and neighbors - Napoleon Hill",
	"Nothing in the world is more common than unsuccessful people with talent.-Anonymous",
	"The function of leadership is to produce more leaders, not more followers.-Ralph Nader",
	"To accomplish great things, we must not only act, but also dream, not only plan, but also believe- Anatole France",
	"Good things come to people who wait, but better things come to those who go out and get them.-Anonymous",
	"Blessed are those who can give without remembering and take without forgetting.-Anonymous",
	"Don't raise your voice, improve your argument.-Anonymous",
	"Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others - John C. Maxwell",
	"Success is liking yourself, liking what you do, and liking how you do it.-Maya Angelou",
	"What seems to us as bitter trials are often blessings in disguise- Oscar Wilde",
	"Opportunities don't happen, you create them.-Chris Grosser",
	"The meaning of life is to find your gift. The purpose of life is to give it away.-Anonymous",
	"Life is not about finding yourself. Life is about creating yourself.-Lolly Daskal",
	"I have not failed. I've just found 10,000 ways that won't work.-Thomas A. Edison",
	"Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.-Swami Vivekananda",
	"Things work out best for those who make the best of how things work out.-John Wooden",
	"Great minds discuss ideas; average minds discuss events; small minds discuss people.-Eleanor Roosevelt",
	"If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work - Thomas J. Watson",
	"Successful entrepreneurs are givers and not takers of positive energy.-Anonymous",
	"If you can't explain it simply, you don't understand it well enough. -Albert Einstein",
	"To live a creative life, we must lose our fear of being wrong.-Anonymous",
	"It is better to fail in originality than to succeed in imitation.-Herman Melville",
	"Our greatest fear should not be of failure but of succeeding at things in life that don't really matter - Francis Chan",
	"You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.-Booker T. Washington",
	"No masterpiece was ever created by a lazy artist- Anonymous",
	"A real entrepreneur is somebody who has no safety net underneath them.-Henry Kravis",
	"Courage is resistance to fear, mastery of fear - not absense of fear- Mark Twain",
	"All our dreams can come true if we have the courage to pursue them.-Walt Disney",
	"When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.-Audre Lorde",
	"Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.-Dr. APJ Kalam ",
	"Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.-Wayne Dyer",
	"When you stop chasing the wrong things you give the right things a chance to catch you.-Lolly Daskal",
	"I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well - Diane Ackerman",
	"To be successful you must accept all challenges that come your way. You can't just accept the ones you like - Mike Gafka",
	"If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it.-Kim Garst",
	"Whenever you find yourself on the side of the majority, it is time to pause and reflect.-Mark Twain",
	"Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.-Nathaniel Hawthorne",
	"I find that when you have a real interest in life and a curious life, that sleep is not the most important thing - Martha Stewart ",
	"Only put off until tomorrow what you are willing to die having left undone.-Pablo Picasso",
	"Try not to become a person of success, but rather try to become a person of value. -Albert Einstein",
	"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.-Mark Caine",
	"There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.-Ella Wheeler Wilcox",
	"The only place where success comes before work is in the dictionary - Vidal Sassoon",
	"If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.- Jim Rohn",
	"You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life - Steve Jobs",
	"The road to success and the road to failure are almost exactly the same.-Colin R. Davis",
	"Do one thing every day that scares you.-Anonymous",
	"People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily - Zig Ziglar",
	"Trust because you are willing to accept the risk, not because it's safe or certain.-Anonymous",
	"It's not what you look at that matters, it's what you see.-Anonymous",
	"If you genuinely want something, don't wait for it -- teach yourself to be impatient.-Gurbaksh Chahal",
	"If you do what you always did, you will get what you always got.-Anonymous",
	"Success is the sum of small efforts, repeated day-in and day-out - Robert Collier",
	"People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.-Tony Robbins",
	"Little minds are tamed and subdued by misfortune; but great minds rise above it.-Washington Irving",
	"Don't let what you cannot do interfere with what you can do.-John R. Wooden",
	"Success does not consist in never making mistakes but in never making the same one a second time.-George Bernard Shaw",
	"The whole secret of a successful life is to find out what is one's destiny to do, and then do it.-Henry Ford",
	"As we look ahead into the next century, leaders will be those who empower others.-Bill Gates",
	"Motivation is what gets you started. Habit is what keeps you going.-Jim Ryun",
	"What's the point of being alive if you don't at least try to do something remarkable.-Anonymous",
	"You may have to fight a battle more than once to win it - Margaret Thatcher",
	"A successful man is one who can lay a firm foundation with the bricks others have thrown at him.-David Brinkley",
	"If you're going through hell keep going - Winston Churchill",
	"If you want to achieve greatness stop asking for permission.-Anonymous",
	"Just when the caterpillar thought the world was ending, he turned into a butterfly.-Proverb",
	"The reason most people never reach their goals is that they don't define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.-Denis Watiley",
	"The distance between insanity and genius is measured only by success.-Bruce Feirstein",
	"The starting point of all achievement is desire.-Napolean Hill",
	"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.-Dale Carnegie",
	"Failure is the condiment that gives success its flavor.-Truman Capote",
	"Your problem isn't the problem. Your reaction is the problem.-Anonymous",
	"All progress takes place outside the comfort zone.-Michael John Bobak",
	"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!-T. Harv Eker",
	"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.-Dale Carnegie",
	"The successful warrior is the average man, with laser-like focus.-Bruce Lee",
	"The best reason to start an organization is to make meaning; to create a product or service to make the world a better place.-Guy Kawasaki",
	"Innovation distinguishes between a leader and a follower.-Steve Jobs",
	"I find that the harder I work, the more luck I seem to have - Thomas Jefferson",
	"Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.-Vaibhav Shah",
	"We become what we think about most of the time, and that's the strangest secret.-Earl Nightingale"
]

module.exports = {
  DSO: require("./src/dso"),
  version: require("./package.json").version,
  randomFact: facts[Math.floor(Math.random() * facts.length)],
  quote: quotes[Math.floor(Math.random() * quotes.length)]
};

